language = "de";
jQuery('.welcome_h1').html("Licht an! Herzlich Willkommen bei Mertex.");
jQuery('#welcome_left').html("<p>Bei uns erhalten Sie individuelle Beleuchtung für Ihr Unternehmen, effizient, hochwertig und zu fairen Preisen.</p><p>In der Zusammenarbeit mit unseren Kunden hören wir erst einmal zu.</p><p>Als Auftragsfertiger bzw. Original Design Manufacturer (ODM) richten wir uns ganz nach Ihren Wünschen und Vorstellung.<br />Das beginnt bereits in der Planung auf Grundlage Ihrer Zeichnungen und Skizzen.<br />Sie erhalten von uns ein funktionsfähiges Muster, das sich eins zu eins in die Massenproduktion überführen lässt.<br />Sie haben besondere technische Anforderungen? Wir freuen uns darauf, Ihre Wünsche zu erfüllen.</p>");
jQuery('#welcome_right').html('<p>Unsere Lampen finden sich in allen Zweigen der Industrie, in der Beleuchtung von Hallen aber auch bei Möbel- und Küchenherstellern sowie Großhändlern.<br />Auf diese Weise gelangen unsere vielseitigen Produkte auch in den Einzelhandel.<br />Auch wir produzieren in China, richten uns dabei jedoch voll und ganz nach deutschen Qualitätsstandards.<br />Und das zu einem attraktiven Preis-Leistungs-Verhältnis. Hinzu kommt, dass die Herstellung unserer LED-Leuchten in eigener Fabrik und mit eigenem Know-how erfolgt.</p><p style="color:#d1ff95;font-style:oblique;">Sprechen Sie uns an.</p>');
jQuery('.About_title').html('Über uns');
jQuery('.Products_title').html('Produkte');
jQuery('.Advantages_title').html('Vorteile');
jQuery('.Individuality_title').html('Individualität');
jQuery('.Quality_title').html('Qualität / Standards');
jQuery('.Versatility_title').html('Vielseitigkeit');
jQuery('.Contact_title').html('Kontakt');
jQuery('#about-us h1').html('Über uns');
jQuery('#products h1').html('Produkte');
jQuery('#advantages h1').html('Vorteile');
jQuery('#individuality h1').html('Individualität');
jQuery('#quality_standards h1').html('Qualität / Standards');
jQuery('#versatility h1').html('Vielseitigkeit');
jQuery('#contact-us h1').html('Kontakt');
jQuery('.contact_us_txt').html('<p><span class="first_text">Mertex</span> ist eine Manufaktur für LED-Beleuchtung und seit 1996 auf dem globalen Markt etabliert. Unser Schwerpunkt liegt dabei auf deutschen Kunden und auch die Forschung und Entwicklung finden am Standort Deutschland statt. Kennzeichnend für unser Unternehmen ist die Etablierung hoher Standards im Bereich Qualitätsmanagement.<br/><br/><span class="first_text">An</span> unserer eigenen Produktionsstätte in China überwachen wir die komplette Herstellung vom Einkauf der Einzelteile bis hin zum fertigen Produkt. Die Unternehmensstrategie von Mertex ist auf Langfristigkeit ausgerichtet. Die meisten unserer Kunden vertrauen uns nun schon seit vielen Jahren und Jahrzehnten. Es handelt sich dabei um eine Reihe namhafter Unternehmen, deren Namen wir jedoch aus Gründen der Diskretion nicht nennen.</p>');
jQuery(".prodcut_first_txt").html('<span class="first_text">Vereinfacht</span> ausgedrückt liefern wir unseren Kunden „alles, was leuchtet“. Konkret bedeutet dies das passgenaue Umsetzen von Beleuchtungslösungen für Unternehmen und Großkunden. Hierzu gehört natürlich auch, dass wir die Steuerung der einzelnen Beleuchtungslösungen übernehmen. Wir lassen dabei keine Fragen offen und liefern stets einen Fullservice.');
jQuery(".product_second_txt").html('<span class="first_text">Unsere</span> Arbeit beginnt meist mit einem Gespräch, in dem das Projekt erörtert und gemeinsam Ideen und Lösungen entwickelt werden. Sofern vorhanden, folgen eine Skizze oder eine Zeichnung des Kunden. Im direkten Dialog mit Ihnen ermitteln wir die Machbarkeit eines Vorhabens und fertigen schließlich ein Musterteil. Sobald wir „grünes Licht“ erhalten, geht es in die Serienproduktion. Selbstverständlich finden auch in diesem Stadium regelmäßige Kontrollen statt, sodass am Ende ein qualitativ hochwertiges und dennoch preisgünstiges Produkt steht.');
jQuery(".prodcut_third_txt").html('<span class="first_text">Dank</span> einer Erfahrung von fast 20 Jahren gelingt uns stets eine individuelle, maßgerechte Lösung. Oder salopp formuliert: wir bringen auch die Augen unserer Kunden zum Leuchten.');
jQuery(".advantages_txt").html('<p class="advantages_txt"><span class="first_text">Die Vorteile</span> einer Zusammenarbeit mit Mertex sind vielfältig. Wir sprechen gerne von drei Säulen, auf denen unser Geschäftsmodell ruht. Im Einzelnen sind dies: Individualität Qualität / Standards Vielseitigkeit</p>');
jQuery(".individuality_txt").html('An erster Stelle steht sicherlich das Erfüllen individueller Wünsche und Vorgaben. Dadurch, dass unsere Leuchten exakt an Ihre Raumverhältnisse angepasst werden, erreichen Sie ein Maximum an Effizienz. Selbstverständlich lässt sich in diesem Kontext auch die Lichtfarbe anpassen und beim Design haben Sie – im Rahmen des Machbaren – völlig freie Hand.');
jQuery(".quality_standards_first_txt").html('<span class="first_text">Qualität</span> ist bei uns deutlich mehr als nur ein Lippenbekenntnis. An unserem Produktionsstandort befinden wir uns im Einklang mit den strengen Vorgaben von VDE und TÜV. Als Kunde profitieren Sie vor allem von der Langlebigkeit unserer Leuchten. Wo anderswo ständig Leuchtmittel ausgewechselt werden müssen, dürfen Sie sich bei uns auf ein jahrelang funktionierendes Produkt freuen. Dadurch, dass wir unsere Kunden bereits seit Jahrzehnten beliefern, haben wir jede Menge Erfahrung mit dem Dauerbetrieb gesammelt und lernen Tag für Tag hinzu.');
jQuery(".quality_standards_second_txt").html('<span class="first_text">Wir</span> wissen, dass Qualität Standards benötigt und externer Kontrollen bedarf. Wir sind uns unserer Verantwortung bewusst und arbeiten nach den strengen Normen des Verbandes der Elektrotechnik Elektronik Informationstechnik (VDE) und des TÜV. Qualität zeigt sich bei uns nicht nur in den verwendeten Materialien und dem Endprodukt, sondern auch in fairen Produktionsbedingungen vor Ort. Im Bereich der Zertifizierungen arbeiten wir mit dem CE- und dem RoHS-Siegel. Mit dem CE- Siegel unterstreichen wir den Einklang mit der Ökodesign- oder ErP-Richtlinie (2009/125/EG, Energierelevante Produkte). Wir stellen somit sicher, dass all unsere Produkte in vollem Umfang den EU-Richtlinien entsprechen.');
jQuery(".quality_standards_third_txt").html('<span class="first_text">Hinter</span> dem RoHS-Siegel verbirgt sich die „Restriction of certain Hazardous Substances“ bzw. die Einschränkung gefährlicher Stoffe. Dadurch, dass wir uns nach den zugehörigen Vorgaben richten, leisten wir einen integralen Beitrag zum Schutz von Umwelt und der Gesundheit unserer Mitarbeiterinnen und Mitarbeiter. In einem Satz: Wir stehen für saubere und gleichzeitig qualitativ hochwertige Produkte.');
jQuery(".versatility_txt").html('Individuelles Design und Produktion nach Wünschen unserer Kunden beinhaltet weit mehr als nur die Umsetzung einer Idee. Wir beraten und begleiten Sie von der ersten Skizze bis zur Serienfertigung. Hinzu kommt, dass wir Sie gerne auch in den Einkauf der Rohstoffe bzw. Einzelteile und die Materialauswahl einbeziehen. Ihr Vorteil: Sie haben während des gesamten Produktionsprozesses lediglich mit einem rundum kompetenten Ansprechpartner zu tun.');
jQuery(".contact_header_txt1").html('Sie sind an einer Zusammenarbeit interessiert? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Oder haben noch offene Fragen?&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Dann lernen Sie uns kennen!');
jQuery(".contact_header_txt2").html('Wir nehmen Beratung persönlich und stehen Ihnen jederzeit gerne Rede und Antwort.');
jQuery(".premission_txt").html('Ich bin damit einverstanden, dass meine Angaben gespeichert werden, um meine Anfrage zu bearbeiten. Selbstverständlich ist die von mir erteilte Einwilligung jederzeit widerrufbar.');
jQuery(".information_txt").html('Meine Daten werden nicht an Dritte weitergegeben.');
jQuery("#send_btn").html('Nachricht senden');
jQuery('#company').attr("placeholder","Unternehmen:");
jQuery('#first_name').attr("placeholder","Vorname:");
jQuery('#last_name').attr("placeholder","Nachname:*");
jQuery('#street').attr("placeholder","Straße:");
jQuery('#house_number').attr("placeholder","Hausnummer:");
jQuery('#country').attr("placeholder","Land:*");
jQuery('#city_code').attr("placeholder","PLZ:");
jQuery('#zipe_code').attr("placeholder","Ort:");
jQuery('#email_address').attr("placeholder","E-Mail Adresse:*");
jQuery('#telephone_number').attr("placeholder","Telefonnummer:*");
jQuery('#subject_line').attr("placeholder","Betreff:");
jQuery('#your_message').attr("placeholder","Ihre Nachricht:*");
jQuery('.disclaimer_text').html('Impressum, Disclaimer und Datenschutzbestimmungen');                          