language = "en";
jQuery('.welcome_h1').html("WELCOME TO MERTEX!");
jQuery('#welcome_left').html("<p>We provide you with customized lighting solutions for your company – efficient high-quality products at fair prices.</p><p>We work hand in hand with our customers and always start out by listening closely to their concerns.</p><p>As a contract manufacturer or Original Design Manufacturer (ODM) we will fully comply with your requests and ideas.<br /> This already starts in the planning phase, when we base our designs on your drawings and sketches.<br />You will receive a working prototype that you can transfer into mass production one-to-one.<br />Do you have any special technical requirements? We look forward to meeting all your needs!</p>");
jQuery('#welcome_right').html('<p>Our lamps can be found in all kinds of industries: In the lighting of manufacturing halls, but also with furniture and kitchen manufacturers as well as wholesalers.<br />That way our wide range of products reaches retailers as well. Our company also manufactures in China like so many others.<br />The big difference is that we comply fully and to the letter with German quality standards and offer you great value for your money.<br />Furthermore, we manufacture our LED lighting in our very own factory utilizing our own know-how.</p><p style="color:#d1ff95;font-style:oblique;">Feel free to contact us with any questions!</p>');
jQuery('.About_title').html('About Us');
jQuery('.Products_title').html('Products');
jQuery('.Advantages_title').html('Advantages');
jQuery('.Individuality_title').html('Individuality');
jQuery('.Quality_title').html('Quality / Standards');
jQuery('.Versatility_title').html('Versatility');
jQuery('.Contact_title').html('Contact Us');
jQuery('#about-us h1').html('About Us');
jQuery('#products h1').html('Products');
jQuery('#advantages h1').html('Advantages');
jQuery('#individuality h1').html('Individuality');
jQuery('#quality_standards h1').html('Quality / Standards');
jQuery('#versatility h1').html('Versatility');
jQuery('#contact-us h1').html('Contact Us');
jQuery('.contact_us_txt').html('<p><span class="first_text">Mertex</span> is a manufacturer of LED lighting and has been firmly established in the global lighting market since 1996. We mainly focus on German customers and our research and development still take place in Germany. Our company is in a class of its own due to its high standards in quality management.<br/><br/><span class="first_text">At</span> our Chinese manufacturing site we monitor the entire production process beginning with the purchase of individual parts to the finished product. Mertex corporate strategy focuses on the long-term. Most of our clients have been trusting us for years and sometimes even decades. Our customers are a series of well-known companies, whose names we choose not reveal for reasons of confidentiality.</p>');
jQuery(".prodcut_first_txt").html('<span class="first_text">Simply</span> put, we provide our customers with “everything that lights up”. More specifically this means that we implement customized lighting solutions for companies and major customers that exactly meet their needs. Part of this approach is of course that we assume complete control of the implementation of individual lighting solutions. We do not leave any questions unanswered and always provide you with a complete service package.');
jQuery(".product_second_txt").html('<span class="first_text">Our</span> cooperation usually begins with an initial conversation, in the course of which we discuss the project at hand and jointly develop ideas and solutions. If available this is followed by a customer sketch or drawing. We will determine the feasibility of the project in direct dialogue with you and subsequently craft a sample. As soon as we receive your “go ahead”, we will start mass-producing your product. It goes without saying that during this phase regular quality controls will take place as well, in order to ensure that a reasonably priced product of high quality is created.');
jQuery(".prodcut_third_txt").html('<span class="first_text">With</span> almost 20 years of experience, we always achieve a customized and tailor-made product solution. Or to put it more casually: We even make the eyes of our clients light up.');
jQuery(".advantages_txt").html('<p class="advantages_txt"><span class="first_text">There</span> are many advantages to joining forces with Mertex. We like to speak about the three pillars our business model is based on. <br/>These are specifically:Individuality Quality/Standards Versatility</p>');
jQuery(".individuality_txt").html('Fulfilling individual requests and specifications certainly comes first. By fitting our lighting products exactly to your spatial conditions, you will achieve a maximum level of efficiency. Obviously the lighting color can also be adjusted while we’re at it and – to the extent possible – you have complete free reign in the design of your product.');
jQuery(".quality_standards_first_txt").html('<span class="first_text">We</span> don’t just pay lip service where quality is concerned. In our manufacturing plant we strictly adhere to the stringent requirements of the VDE (German Electrotechnology Association) and the TÜV (Technischer Überwachungsverein). As our customer, you particularly get to benefit from the longevity of our lighting products. Whereas with other lighting products the illuminants have to constantly be replaced, you get to enjoy many years of a fully functioning product with our lighting solutions. As we have been supplying our customers for many years, we have gained a lot of experience with the permanent use of our products and continue to learn every day.');
jQuery(".quality_standards_second_txt").html('<span class="first_text">We</span> know that quality requires standards and external controls. We are fully aware of our responsibilities and work according to the strict standards of the German Electrotechnology Association (VDE) and the Technischer Überwachungsverein (TÜV). We don’t just demonstrate quality in the choice of materials used for production and our final products, but also in ensuring fair manufacturing conditions on-site.');
jQuery(".quality_standards_third_txt").html('<span class="first_text">As</span> far as certifications are concerned, we are in compliance with the CE (European Conformity) and RoHS (Restriction of Hazardous Substances) directives.  By complying with the CE directive, we stress our conformance with the eco-design and ErP (2009/125/EG Energy related Products) directives. This way we ensure that all of our products are fully compliant with European standards and directives. The RoHS directive contains the „Restriction of certain Hazardous Substances“. As we comply with the corresponding guidelines, we make an active contribution to protect the environment and the health of our employees. To summarize: We stand for clean products of the highest quality.');
jQuery(".versatility_txt").html('The creation of individual designs and the manufacture of products according to the wishes of our customers mean much more than simply putting ideas into practice. We advise and assist you from the first sketch all the way to the start of mass production. Furthermore, we’ll gladly let you be a part of the purchase of raw materials and components as well as the selection of materials. Your advantage: During the entire production process, you will only interact with one fully competent contact person.');
jQuery(".contact_header_txt1").html('Are you interested in working with us? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Do you have any questions?&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Then you should get to know us!');
jQuery(".contact_header_txt2").html('We take consultations personally and are always available to answer your questions.');
jQuery(".premission_txt").html('I give my permission that this information will be saved, in order to process my inquiry. Naturally, I can withdraw the permission granted at any time.');
jQuery(".information_txt").html('My information will not be shared with third parties.');
jQuery("#send_btn").html('Send message');
jQuery('#company').attr("placeholder","Company:");
jQuery('#first_name').attr("placeholder","First Name:");
jQuery('#last_name').attr("placeholder","Last Name:*");
jQuery('#street').attr("placeholder","Street:");
jQuery('#house_number').attr("placeholder","House number:");
jQuery('#country').attr("placeholder","Country:*");
jQuery('#city_code').attr("placeholder","City code:");
jQuery('#zipe_code').attr("placeholder","Zipe code:");
jQuery('#email_address').attr("placeholder","Email address:*");
jQuery('#telephone_number').attr("placeholder","Telephone number:*");
jQuery('#subject_line').attr("placeholder","Subject line:");
jQuery('#your_message').attr("placeholder","Your message:*");  
jQuery('.disclaimer_text').html('Site notice, disclaimer and privacy statement');                                  